//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace COSC4210.MusicalIntruments.Web {
    
    
    public partial class Homework7 {
        
        /// <summary>
        /// userControlCollectIt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::COSC4210.MusicalIntruments.Web.Control.CollectItemControl userControlCollectIt;
        
        /// <summary>
        /// userControlDisplayIt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::COSC4210.MusicalIntruments.Web.Control.DisplayInfoControl userControlDisplayIt;
    }
}
